
public enum Tag
{

	NN, VVFIN, ART, ADJD, APPR, PPOSAT, PTKVZ, CARD, APPRART, VAFIN, ADV, KONJ, NE, ADJA, PIDAT, PDAT, VMINF, PROAV, VMFIN, VVINF, PRELS, PPER, KOUI, PTKZU, PRF, VVPP, PTKNEG, KOUS, $, KON, PIS, VVIZU, KOKOM, VAPP, FM, PWAV, XY, VAINF, PDS, PIAT, APPO, TRUNC, PWS, PTKA, APZR, VVIMP, PRELAT, VAIZU, PWAT, ITJ, PPOSS, PTKANT, VMPP
}
